=== teuton-software/jasker/src/main/resources/schema/asker.xsd
<xsd:schema 
	version="2.6.0" 
	targetNamespace="http://io.github.teuton-software/asker" 
	xmlns="http://io.github.teuton-software/asker"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"	
	elementFormDefault="qualified">

	<xsd:element name="map" type="mapType" xsi:schemaLocation="" />

	<xsd:complexType name="mapType">
		<xsd:sequence>
			<xsd:choice maxOccurs="unbounded">
				<xsd:element name="concept" type="conceptType" />
				<xsd:element name="code" type="codeType" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="context" type="xsd:string" use="required" />
		<xsd:attribute name="lang" type="xsd:string" use="required" />
		<xsd:attribute name="version" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="conceptType">
		<xsd:sequence>	
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="tags" type="xsd:string" />
				<xsd:element name="def" type="defType" />
				<xsd:element name="table" type="tableType" />
			</xsd:choice>
			<xsd:element name="names" type="xsd:string" />
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="tags" type="xsd:string" />
				<xsd:element name="def" type="defType" />
				<xsd:element name="table" type="tableType" />
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="defType" mixed="true">
		<xsd:attribute name="type" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="tableType">
		<xsd:sequence>
			<xsd:element name="row" type="rowType" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="fields" type="xsd:string" use="required" />
		<xsd:attribute name="sequence" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:complexType name="rowType" mixed="true">	
		<xsd:sequence>
			<xsd:element name="col" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>	
	</xsd:complexType>
	
	<xsd:complexType name="codeType">
		<xsd:all>
			<xsd:element name="type" type="xsd:string" minOccurs="1"/>
			<xsd:element name="path" type="xsd:string" minOccurs="1"/>
		</xsd:all>
	</xsd:complexType>	

</xsd:schema>

=== teuton-software/jasker/output.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<map xmlns="http://io.github.teuton-software/asker" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" lang="en" context="music, band" version="1" xsi:schemaLocation="http://io.github.teuton-software/asker src/main/resources/schema/asker.xsd">
    <concept>
        <names>nam1, name2</names>
        <tags>tag1, tag2, tag3</tags>
        <def type="text">def1</def>
        <def type="text">def2</def>
        <def type="text">def3</def>
        <table fields="col1, col2" sequence="seq">
            <row>
                <col>rowValue</col>
            </row>
            <row>
                <col>colValue</col>
            </row>
        </table>
        <table fields=""/>
    </concept>
    <code>
        <type>python</type>
        <path>files\arrays.py</path>
    </code>
</map>
